### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ARK-04** [CTownsend20/OOPA01#1]
You're off to a good start - the pack is being created successfully, all your error handling is in place, the shuffles are close to functioning and the singular deal code is correct. A few critiques on what you have so far:

- The commenting you have done is clear but it might be worth adding more to explain why you have added certain things.
- Everything is happening in the pack class (except for card creation) so it would be worth moving the user input instructions and inputs to Main since testing does not take input from the user – this way you can pass the inputs into the class functions when you call them as well as preselect the values in the testing class (e.g. Pack.shuffleCard(userInput) VS Pack.shufflePack(testingValue))
- You should also move the deal options into a different function or into Main as it is unnecessary repetition to have it after type of shuffle.

**Comment by CTownsend20** [comment]
Thank you for your feedback, I will take it into account when I write the rest of my code.
