### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by amb64** [CTownsend20/OOPA01#2]
I think you've done a good job on your code so far! You've used comments well to document what goes on where in your program.

I can see you've started to implement the shuffles, and your fisher yates shuffle looks good, its very concise and even though I can't see the output, it seems to be correct.

I can also see you've implemented the methods to deal one and multiple cards. Your error handling here is good, as the program does not allow erroneous input such as big or small numbers, letters, etc! Unfortunately, the program runs into an error when you try to deal multiple cards.

At the moment, for what you have implemented, you have done well! My only suggestions for improvement are of course to fix the bugs and to finish your implementation of the shuffles and dealing methods, as well as the testing class. Good job so far!!

**Comment by CTownsend20** [comment]
Thank you for your review, I will definitely take your feedback into account when I go through my code.
